name: Continuous Integration

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  cross-platform-build:
    name: Native builds & tests
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5.1
    with:
      duckdb_version: v1.5.1
      ci_tools_version: v1.5.1
      extension_name: gdx
      build_type: release
      upload_all_extensions: false
      exclude_archs: 'linux_arm64;linux_amd64_musl;windows_amd64_mingw'
